### ISSUE TITLE
ReferenceError: script is not defined

### ISSUE THREAD

**Issue by marcoraddatz** [jacopotarantino/ng-optimizely#16]
Hi,

I got following ReferenceErrors:

`ReferenceError: script is not defined`
`ReferenceError: first is not defined`

By adding a "var" I fixed them:

`var script = document.createElement('script');`instead of `script = document.createElement('script');` and `var first = document.getElementsByTagName('script')[0];`.

Maybe this also helps other people. I'm sorry that I didn't do a PR.

Thanks!
Marco

**Comment by jacopotarantino** [comment]
Merged the PR. Thanks again!
