### ISSUE TITLE
Thunderhead ONE plugin

### ISSUE THREAD

**Issue by ghost** [jacopotarantino/ng-optimizely#18]
Not an issue, but a note. Based on your work I made a plugin for [Thunderhead ONE](https://www.thunderhead.com/one-engagement-hub/). Thanks for your solution and [article](https://jack.ofspades.com/angular-optimizely/index.html)!

https://www.npmjs.com/package/ng-thunderhead

**Comment by xeeo** [comment]
Great!

**Comment by jacopotarantino** [comment]
@roelal nice work! thanks for letting me know, that makes me really happy that i could help.
