### ISSUE TITLE
Missing angular dependency in bower.json

### ISSUE THREAD

**Issue by pmowrer** [jacopotarantino/ng-optimizely#2]
It's obvious of course, but it would be helpful to make it explicit in `bower.json` since bower tooling, like [main-bower-files](https://github.com/ck86/main-bower-files), sort by order of dependency.

**Comment by jacopotarantino** [comment]
Hah. That's a very good point. I'm surprised I overlooked that. Must have been thinking of dev-dependencies or something. https://github.com/jacopotarantino/ng-optimizely/commit/60dacc53664122792a74ffa350c457441484b6f7 should fix the issue. Let me know if you have any problems.

**Comment by jacopotarantino** [comment]
Oh, also, I bumped the version so you should be able to use that right away.

**Comment by pmowrer** [comment]
Thanks!
