### ISSUE TITLE
Using Directive With Redirects

### ISSUE THREAD

**Issue by jackpower** [jacopotarantino/ng-optimizely#5]
Hi,

Great plug-in works like a charm for most of the stuff that I want to do. One issue I have run into though is when trying to use a url redirect experiment, i.e. not using the in-built optimizely editor. When I try to run this experiment it does not work as intended, in fact it just shows a blank screen.

I remember you saying in your article that the editing should be done in the optimizely editor. Is there any way to make the directive work with url redirect experiments as well?

Thanks!

Jack

**Comment by jacopotarantino** [comment]
Hey, thanks for the feedback! It means a lot.
Hmm.. Just off the top of my head I'm assuming that Optimizely is either looking at an HTTP request header and determining what to run off of that or it's sending scripts that use something like `window.location.href`. If it's the former, I'm not sure there's a proper way to do a redirect experiment within Optimizely's normal workflow. If it's the latter you should just be able to trigger the experiments in the normal way and I would assume it works.

If you can't figure it out, perhaps a good way to move forward would be to create a new experiment with a custom script and just run `document.location = `http://example.com'` manually. Maybe triggering a custom optimizely event before you do so to make sure you can track your goals accurately.

Let me know if that works out for you!

**Comment by jacopotarantino** [comment]
Closing this as outdated for now. Feel free to reopen with new comments.
