### ISSUE TITLE
A way to change the $rootScope event name

### ISSUE THREAD

**Issue by ryeballar** [jacopotarantino/ng-optimizely#6]
As what is happening right now, `ng-optimizely` is listening to the `$viewContentLoaded` event. It would be good to have a way to change it in the `loadProject()` function for those who are using `ui-router`. The problem is that `$viewContentLoaded` triggers everytime a view is loaded, and `ui-router` offers a possibility to load nested and multiple views. Thus, when an application has 5 levels of nested views then the manual activation also triggers 5 times. If you're asking for the event name suitable for `ui-router` it would be `$stateChangeSuccess`

**Comment by jacopotarantino** [comment]
@ryeballar interesting! I hadn't tested for that before. `ui-router` integration is definitely a case I'd like to support. Could you send a PR with your proposed changes? Even something crappy just to give me a starting point would be greatly appreciated.

**Comment by motin** [comment]
A comment: I've added this ability, and using $stateChangeSuccess prevents triple/quadruple activation of optimizely. However, using $viewContentLoaded seems to lessen the risk for FOUC since the $stateChangeSuccess event is triggered quite late in the DOM loading process.

**Comment by jacopotarantino** [comment]
Just because it's not clear from the GH note: This was closed by merging in the PR which addresses the issue. Thanks all!
