### ISSUE TITLE
Please release the newest code as new bower-package-version

### ISSUE THREAD

**Issue by rvetere** [jacopotarantino/ng-optimizely#9]
Hi there,

great plugin, big time-safer so far :-) In our project, we're using ui-router and so i've integrated optimizely with a "resolve" approach, working great so far.

But now i'm facing that the $viewContentLoaded event is fired up to 4 times for a single state change - resulting in multiple executions of the same experiment which is, not very cool.

I was just about to update the code, make a fork and so on... Until i realized that your newest code here in the repo is already aware of that - i mean, your newest example of "loadProject" in the readme.md is showing an event-name besides the optimizely-id -> which is only working with the latest code.

But i just installed it through bower install - which is integrating the version "0.2.1" of your plugin - which is NOT including those latest changes..

Now, we would really appreciate it if it would be possible to make a new version, maybe "0.2.2", which integrates this latest changes to actually define the event which is bound to the optimizely "activate".

Currently i just changed the code manually in our project - but as soon as somebody re-installs everything, the old 0.2.1 code will get active again.. you know the struggles which results of such things...

Thanks in advance, keep up the good work!

Regards
Remo

**Comment by jacopotarantino** [comment]
Hey @rvetere! Thanks for the reminder. ng-optimizely is now available as version 0.2.2 as of commit https://github.com/jacopotarantino/ng-optimizely/commit/bd22b969861cb450ca55050a4a8ccb5bf8e0739e
